### ISSUE TITLE
Change drive location to My Shared Drive ?

### ISSUE THREAD

**Issue by JohnCale47** [shubham8550/Google-Drive-Torrent-Downlaoder#1]
**Anyway to Change drive location to My Shared Drive ?**

**Comment by shubham8550** [comment]
If you mean Shared Folder then 
### Create a Shortcut of your shared folder in "My Drive"  
![Annotation 2020-12-30 222336](https://user-images.githubusercontent.com/35478603/103368522-bc318a80-4aed-11eb-8f81-30af19588733.png)

**then change save_path in step 4**
![Capture](https://user-images.githubusercontent.com/35478603/103368646-20ece500-4aee-11eb-9aaa-32e8b994ca26.JPG)
